name: Deploy to Server

on:
  push:
    branches:
      - master  # 你可以根据需求调整触发条件，例如推送到特定分支时触发部署

jobs:
  deploy:
    runs-on: windows-latest  # 运行环境为 Windows
    
    steps:
      # Checkout代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 SSH 密钥
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # GitHub Secrets 中存储的私钥

      # 确保 SSH 密钥文件权限正确
      - name: Fix SSH file permissions
        run: |
          icacls "C:\Users\runneradmin\.ssh\id_rsa" /inheritance:r /grant:r "%username%:F"  # 修改文件权限确保可访问

      # 添加目标主机到 known_hosts 以避免第一次连接时的提示
      - name: Add server to known hosts
        run: |
          ssh-keyscan -H 120.55.102.193 >> C:\Users\runneradmin\.ssh\known_hosts

      # 使用 SSH 执行部署命令
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no Administrator@120.55.102.193 "cd C:\Users\Administrator\Desktop\my-app\Online-Restaurant\build && git pull origin master && ./deploy.sh"
