name: Deploy to Server

on:
  push:
    branches:
      - master  # 你可以根据需求调整触发条件，例如推送到特定分支时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest 
    
    steps:
      # Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 SSH 密钥
      - name: Create SSH private key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 添加目标主机到 known_hosts 以避免第一次连接时的提示
      - name: Add server to known hosts
        run: |
          ssh-keyscan -H 121.40.103.76 >> ~/.ssh/known_hosts

      # SSH 连接到服务器并拉取最新代码
      - name: SSH into server and pull latest changes
        run: |
         ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -o ServerAliveInterval=60 root@121.40.103.76 << 'EOF'
            # 确保目标目录存在
            cd /home/www/myapp/Online-Restaurant || exit 1

            # 拉取最新代码
            git pull origin master || exit 1

            # 安装依赖
            npm install --force --verbose || exit 1

            # 构建 React 应用
            npm run build || exit 1

            # 重启 Nginx 服务
            sudo systemctl restart nginx || exit 1
EOF
