name: Deploy to Server

on:
  push:
    branches:
      - master  # 你可以根据需求调整触发条件，例如推送到特定分支时触发部署

jobs:
  deploy:
    runs-on: windows-latest  # 运行环境为 Windows
    
    steps:
      # Checkout代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 SSH 密钥
      - name: Create SSH private key file
        run: |
          New-Item -ItemType File -Force -Path "C:\Users\runneradmin\.ssh\id_rsa"
          $privateKey = "${{ secrets.SSH_PRIVATE_KEY }}"
          $privateKey | Set-Content -Path "C:\Users\runneradmin\.ssh\id_rsa" -Force

      # 确保 SSH 密钥文件权限正确
      - name: Fix SSH file permissions
        run: |
          icacls "C:\Users\runneradmin\.ssh\id_rsa" /inheritance:r /grant:r "runneradmin:F"  # 设置权限

      # 添加目标主机到 known_hosts 以避免第一次连接时的提示
      - name: Add server to known hosts
        run: |
          ssh-keyscan -H 120.55.102.193 >> C:\Users\runneradmin\.ssh\known_hosts
          
 # SSH连接到服务器并拉取代码
      - name: SSH into server and pull latest changes
        run: |
ssh -v -i C:\Users\runneradmin\.ssh\id_rsa -o StrictHostKeyChecking=no Administrator@120.55.102.193 "cd C:\Users\Administrator\Desktop\my-app\Online-Restaurant && git pull origin master"
