name: Deploy React App to Windows ECS

on:
  push:
    branches:
      - master  # 触发规则：当推送到 master 分支时触发部署流程

jobs:
  deploy:
    runs-on: windows-latest  # 在 GitHub Actions 的 Windows 环境下运行

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up SSH key for secure communication with server
      - name: Set up SSH key
        run: |
          # 创建 SSH 文件夹并添加私钥
          mkdir C:\Users\runneradmin\.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > C:\Users\runneradmin\.ssh\id_rsa
          # 确保权限是 600
          icacls C:\Users\runneradmin\.ssh\id_rsa /inheritance:r
          icacls C:\Users\runneradmin\.ssh\id_rsa /grant:r "${{ runner.os }}:(R)"
          # 配置跳过主机验证
          echo "Host *" > C:\Users\runneradmin\.ssh\config
          echo "  StrictHostKeyChecking no" >> C:\Users\runneradmin\.ssh\config

      # 3. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 使用你项目需要的 Node.js 版本

      # 4. Install dependencies and build the React app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 5. Deploy to Windows Server (ECS)
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no Administrator@120.55.102.193 "cd C:\Users\Administrator\Desktop\my-app\Online-Restaurant && git pull && npm install && npm run build && pm2 restart all"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
